# Use an Ubuntu base image
FROM ubuntu:22.04

# Update package lists and install OpenJDK 17
RUN apt-get update && \
    apt-get install -y openjdk-17-jre-headless

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container at /app
COPY build/libs/demo-0.0.1-SNAPSHOT.jar /app/demo.jar

# Expose the port the application runs on
EXPOSE 8080

# Specify the command to run your application
CMD ["java", "-jar", "demo.jar"]

# docker build -f /Users/kongphobwutthiumphol/Desktop/GeminiPj/DockerFile -t spring-boot-app /Users/kongphobwutthiumphol/Desktop/GeminiPj
# docker run -p 8080:8080 spring-boot-app
# docker rm -f spring-boot